### ISSUE TITLE
Special Characters 

### ISSUE THREAD

**Issue by svenjaun** [nailsframework/nailsjs#4]
**Describe the bug**
Sanitizer doesn't work with special Characters, such as / @ etc.

**To Reproduce**
1. Create Nails APP'
2. Create State
3. Add State with Special Character
4. Show it on the Website with the Sanitizer

PLS FIX THX

**Comment by svenjaun** [comment]
Here the JSON i used 
[{
          "name": "Dominic Jaermann",
          "title": "Briefkasten",
          "text": "Ein Briefkasten eines einheimischen",
          "ISO": "100",
          "Brennweite": "4.8mm",
          "Blende": "f/3.2",
          "Verschlusszeit": "1/100 Sek."
      },
      {
          "name": "Dominic Jaermann",
          "title": "Grill",
          "text": "Text zu Grill",
          "ISO": "100",
          "Brennweite": "11.5mm",
          "Blende": "f\/3.4",
          "Verschlusszeit": "1/50 Sek."
      },
      {
          "name": "Dominic Jaermann",
          "title": "Monolith",
          "text": "Ein Monolith",
          "ISO": "100",
          "Brennweite": "4.8mm",
          "Blende": "f\/2.8",
          "Verschlusszeit": "1/40 Sek."
      },
      {
          "name": "Mladen Brankovic",
          "title": "Giraffe",
          "text": "Eine Giraffe",
          "ISO": "100",
          "Brennweite": "4.8mm",
          "Blende": "f\/2.8",
          "Verschlusszeit": "1/80 Sek."
      },
      {
          "name": "Mladen Brankovic",
          "title": "Skulptur",
          "text": "Eine Skulptur",
          "ISO": "100",
          "Brennweite": "4.8mm",
          "Blende": "f\/4.0",
          "Verschlusszeit": "1/200 Sek."
      },
      {
          "name": "Mladen Brankovic",
          "title": "Verkehrshut",
          "text": "Ein Verkehrshut",
          "ISO": "100",
          "Brennweite": "8.5mm",
          "Blende": "f\/3.2",
          "Verschlusszeit": "1/80 Sek."
      },
      {
          "name": "Sven Jaun",
          "title": "Fanta",
          "text": "Eine Fanta",
          "ISO": "100",
          "Brennweite": "9.2mm",
          "Blende": "f\/3.2",
          "Verschlusszeit": "1/40 Sek."
      },
      {
          "name": "Sven Jaun",
          "title": "Trottinett",
          "text": "Ein Trottinett",
          "ISO": "100",
          "Brennweite": "8mm",
          "Blende": "f\/3.0",
          "Verschlusszeit": "1/100 Sek."
      },
      {
          "name": "Sven Jaun",
          "title": "Tuerschloss",
          "text": "Eine Tuerschloss",
          "ISO": "100",
          "Brennweite": "38.5mm",
          "Blende": "f\/3.7",
          "Verschlusszeit": "1/60 Sek."
      }]

**Comment by p493z3r0** [comment]
Bug was fixed here: https://github.com/nailsframework/nails/commit/ac4318e73e20eef0a1c8e18188feb14538e48b86
